# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='Accounts',
        ),
    ]
