# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregapp', '0002_auto_20190221_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
