# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-20 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0002_authors_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.AddField(
            model_name='books',
            name='id',
            field=models.ManyToManyField(related_name='book', to='lit.authors'),
        ),
        migrations.RemoveField(
            model_name='books',
            name='title',
        ),
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.CharField(default='asdf', max_length=255),
            preserve_default=False,
        ),
    ]
