# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-20 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0003_auto_20190219_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
