# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-20 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0004_auto_20190219_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(default=False),
        ),
    ]
