# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-20 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0005_auto_20190219_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.AddField(
            model_name='books',
            name='id',
            field=models.AutoField(auto_created=True, default=False, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='books',
            name='title',
        ),
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.ManyToManyField(related_name='book', to='lit.authors'),
        ),
    ]
