# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0007_auto_20190219_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(max_length=255),
        ),
    ]
